"""Abstract storage backend protocol."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from capsule_trace.core.models import Event, SessionMetadata


@runtime_checkable
class StorageBackend(Protocol):
    def write_event(self, event: Event) -> None: ...

    def write_cassette(self, cassette_id: str, data: dict[str, Any]) -> None: ...

    def write_snapshot(self, step_index: int, snapshot: dict[str, Any]) -> None: ...

    def read_session_metadata(self, session_id: str) -> SessionMetadata: ...

    def read_events(self, session_id: str) -> list[Event]: ...

    def read_cassettes(self, session_id: str) -> dict[str, Any]: ...

    def read_snapshots(self, session_id: str) -> dict[int, Any]: ...

    def finalize_session(self, metadata: SessionMetadata) -> None: ...

    def list_sessions(self, limit: int = 50) -> list[SessionMetadata]: ...

    def delete_session(self, session_id: str) -> None: ...
